version: "3"

env:
  APP_ENV: '{{default "dev" .APP_ENV}}'
  API_VERSION: '{{default "0.1.0" .API_VERSION}}'
  UI_VERSION: '{{default "0.1.0" .UI_VERSION}}'

dotenv: [".env.{{.APP_ENV}}", ".env"]

tasks:
  deps:
    cmds:
      - npm install -g json-schema-to-typescript

  genid:
    cmds:
      - uv run cli exercises generate-uuid

  export-exercises:
    cmds:
      - uv run cli exercises export-json

  export-ts:
    cmds:
      - uv run pydantic2ts --module exdb_data.schemas --output schemas.ts
